### ISSUE TITLE
Error 404 not found on deployment section

### ISSUE THREAD

**Issue by sparkingdark** [canturan10/satellighte#3]
When I click on fastapi or onnx lik to check for deployment it gives error 404, but they are checked .

**Comment by canturan10** [comment]
Hello There 👋
Yes, the problem you mentioned is available in [pypi](https://pypi.org/project/satellighte/) and[ web page](https://canturan10.github.io/satellighte), but there is no problem in [readme.md on github](https://github.com/canturan10/satellighte/blob/master/README.md). There was such a problem because it was broadcast directly through the readme.md file. I will fix this in the next release. Until then, issue may remain open.
Thank you.

**Comment by canturan10** [comment]
I'm closing the issue as the issue you mentioned has been resolved with v0.1.1.
Thank you.
