### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by protestToViolence** [canturan10/satellighte#4]
Hello,
I could not find the working examples of the models getting results on the tiff images. The documentation does not makes it clear how to install the model orit is preintsalled. I created a separate conda environment for this package. So needed to test upon sentinel and eurosat images.

**Comment by canturan10** [comment]
Hello There 👋
I'm surprised you asked for an example because I think I've made the necessary explanations. For example, 

- if you look at the `readme.md` file, the example usage is explained in the [`usage-examples` ](https://github.com/canturan10/satellighte#usage-examples)section. 

- There is even inference code in the [`demo.py`](https://github.com/canturan10/satellighte/blob/master/demo.py) file that you can run directly.

If these explanations are not sufficient for you, I can provide information on how to install from the beginning.
Thank you.

**Comment by protestToViolence** [comment]
Hello Sir,
Thank you for replying. And yes demo.py did helped me to classify aerial images as residential. I am grateful for you providing such wonderful content. It was my mistake that i did not get answers from usage-examples. But demo.py helped me a lot.
Again grtitude to you for doing so much for satellite image inference usage.
Thank you,

**Comment by canturan10** [comment]
Thank you for your nice review. I will work to further develop the project. You can stay tuned :)

Now that we've fixed the issue, I'm closing the issue.
